Repository tf-wallet-dscanner/tf-wallet, pull requests merged in 2022-09, with the labels that each got.

#56 test: keyring-controller test 작성
  package.json
  src/app/controllers/keyring-controller.js
  src/app/controllers/keyring-controller.test.js
  src/app/lib/web3-query.js
  src/app/mocks/mock-encryptor.js
Labels: size/L, test

#60 52 token controller
  .yarn/cache/ethereumjs-abi-npm-0.6.8-c911e0a245-cede2a8ae7.zip
  package.json
  src/app/background.js
  src/app/contracts/ERC20.json
  src/app/contracts/ERC721.json
  src/app/controller.js
  src/app/controllers/token-controller.js
  src/app/lib/util.js
  src/app/lib/web3-query.js
  src/app/messages.js
  src/ui/data/token/index.js
  src/ui/data/token/token.api.js
  src/ui/data/token/token.hooks.js
  src/ui/pages/home.jsx
  src/ui/pages/index.jsx
  src/ui/pages/routing.jsx
  src/ui/pages/token.jsx
  yarn.lock
Labels: size/XXL

#61 feat: transaction + gas 기능 개발
  .yarn/cache/caniuse-lite-npm-1.0.30001319-17883c730d-1c03cc4ca0.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001399-96a5592f00-dd105b06fb.zip
  src/app/background.js
  src/app/constants/gas.js
  src/app/controller.js
  src/app/controllers/transactions/transaction-controller.js
  src/app/controllers/transactions/tx-gas-utils.js
  src/app/controllers/transactions/tx-util.js
  src/app/lib/util.js
  src/app/messages.js
  src/ui/data/transaction/transaction.api.js
  src/ui/data/transaction/transaction.hooks.js
  src/ui/pages/transaction/estimate-gas.jsx
  src/ui/pages/transaction/input-address.jsx
  src/ui/pages/transaction/transaction.jsx
  src/ui/pages/transaction/tx-result.jsx
  src/ui/store/transaction.js
  yarn.lock
Labels: feature, size/L

#66 account API 호출형태 변경, keystore to private key 추출 기능 추가
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/controllers/keyring-controller.test.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/data/account/account.hooks.js
  src/ui/pages/import-account.jsx
  src/ui/pages/json-file.jsx
  src/ui/pages/new-account.jsx
Labels: refactor, size/XL

#67 65 erc 20 transfer
  .env.sample
  .yarn/cache/ethereumjs-common-npm-1.5.2-7a721136f7-3fc64faced.zip
  .yarn/cache/ethereumjs-tx-npm-2.1.2-2a70e164aa-a5b607b4e1.zip
  contracts/ERC20.json
  contracts/ERC721.json
  deploy/README.md
  deploy/deploy-erc20.js
  deploy/transfer-erc20.js
  package.json
  src/app/background.js
  src/app/controller.js
  src/app/controllers/token-controller.js
  src/app/controllers/transactions/transaction-controller.js
  src/app/lib/util.js
  src/app/messages.js
  src/ui/data/token/token.api.js
  src/ui/data/token/token.hooks.js
  src/ui/pages/routing.jsx
  src/ui/pages/token.jsx
  src/ui/pages/transaction/estimate-gas.jsx
  src/ui/pages/transaction/index.js
  src/ui/pages/transaction/input-address-token.jsx
  src/ui/pages/transaction/transaction.jsx
  src/ui/store/transaction.js
  yarn.lock
Labels: size/XL

#69 nonceTracker 추가
  .eslintrc.js
  .yarn/cache/@metamask-metamask-eth-abis-npm-3.0.0-372e3b8aec-a9e3020dd8.zip
  .yarn/cache/await-semaphore-npm-0.1.3-b7a0001fab-334c86541e.zip
  .yarn/cache/fast-json-patch-npm-3.1.1-7e8bb70a45-c4525b61b2.zip
  package.json
  src/app/background.js
  src/app/constants/app.js
  src/app/controller.js
  src/app/controllers/provider-controller.js
  src/app/controllers/transactions/lib/util.js
  src/app/controllers/transactions/pending-tx-tracker.js
  src/app/controllers/transactions/transaction-controller.js
  src/app/controllers/transactions/tx-state-manager.js
  src/app/lib/createInfuraClient.js
  src/app/lib/createJsonRpcClient.js
  src/app/lib/nonce-tracker.js
  src/app/messages.js
  src/app/modules/contract-utils.js
  src/app/modules/hexstring-utils.js
  src/app/modules/random-id.js
  src/app/modules/string-utils.js
  src/app/modules/transaction.utils.js
  src/ui/data/transaction/transaction.api.js
  src/ui/data/transaction/transaction.hooks.js
  src/ui/helpers/constants/common.js
  src/ui/pages/home.jsx
  src/ui/pages/transaction/estimate-gas.jsx
  src/ui/pages/transaction/input-address.jsx
  src/ui/pages/transaction/tx-result.jsx
  yarn.lock
Labels: feature, size/XXL

#70 vault 관련 수정
  src/app/controllers/keyring-controller.js
  src/ui/pages/json-file.jsx
Labels: refactor, size/M

#71 graphql api 추가
  src/app/background.js
  src/app/controller.js
  src/app/controllers/history-controller.js
  src/app/messages.js
  src/ui/data/history/history.api.js
  src/ui/data/history/history.hooks.js
  src/ui/pages/eth-history.jsx
Labels: feature, size/L

#73 estimateGas error fix
  src/app/constants/gas.js
  src/app/controller.js
  src/app/controllers/transactions/transaction-controller.js
  src/app/controllers/transactions/tx-gas-utils.js
  src/ui/pages/home.jsx
  src/ui/pages/transaction/estimate-gas.jsx
  src/ui/pages/transaction/input-address.jsx
  src/ui/store/transaction.js
Labels: bug, size/M

#75 feat: home 화면에 balance 표기
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/controllers/transactions/transaction-controller.js
  src/ui/pages/home.jsx
  src/ui/pages/json-file.jsx
Labels: size/L
