Repository tf-wallet-dscanner/tf-wallet, pull requests merged in 2022-11, with the labels that each got.

#99 refactor: token gas estimate 로직 수정
  public/notification.html
  public/popup.html
  src/app/background.js
  src/app/controller.js
  src/app/controllers/transactions/transaction-controller.js
  src/app/messages.js
  src/ui/data/transaction/transaction.api.js
  src/ui/data/transaction/transaction.hooks.js
  src/ui/pages/transaction/estimate-gas.jsx
  src/ui/pages/transaction/transaction.jsx
  src/ui/pages/transfer/estimate-token-gas.jsx
  src/ui/pages/transfer/input-address-token.jsx
  src/ui/pages/transfer/transfer.jsx
  src/ui/store/transaction.js
Labels: refactor, size/L

#101 account identities에 키링 type 정보 추가
  src/app/controllers/keyring-controller.js
  src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
  src/ui/components/account-view/dropdown-menu/dropdown-menu.scss
Labels: feature, size/S

#102 keystoreV4 import/export 추가
  package.json
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/lib/account-importer.js
  src/app/lib/caver/index.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/data/account/account.hooks.js
  src/ui/pages/export-account.jsx
  yarn.lock
Labels: feature, size/L
