Repository tf-wallet-dscanner/tf-wallet, pull requests merged in 2022-08, with the labels that each got.

#35 feat: keyring-controller 추가
  .pnp.cjs
  .yarn/cache/@types-node-npm-11.11.6-40abad0842-075f1c011c.zip
  .yarn/cache/aes-js-npm-3.1.2-d7549a23a2-062154d50b.zip
  .yarn/cache/bip39-npm-3.0.4-7c69c9182f-79ce1600a0.zip
  .yarn/cache/browser-passworder-npm-2.0.3-ba40718b76-df3ec46e10.zip
  .yarn/cache/browserify-unibabel-npm-3.0.0-c9662fecbe-fe1b502c09.zip
  .yarn/cache/ethereumjs-wallet-npm-1.0.2-8a504d268d-555effe571.zip
  config/webpack.config.js
  package.json
  src/app/background.js
  src/app/controllers/keyring-controller.js
  src/app/lib/hd-keyring.js
  src/app/lib/simple-keyring.js
  src/app/lib/util.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/data/account/index.js
  src/ui/pages/account.jsx
  src/ui/pages/home.jsx
  src/ui/pages/routing.jsx
  yarn.lock
Labels: feature, size/XL

#39 feat: 계정복구, 개인키, 공개키 추출 기능 추가
  src/app/background.js
  src/app/contentscript.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/inpage.js
  src/app/lib/hd-keyring.js
  src/app/lib/simple-keyring.js
  src/app/lib/util.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/pages/home.jsx
  src/ui/pages/import-account.jsx
  src/ui/pages/new-account.jsx
  src/ui/pages/routing.jsx
Labels: feature, size/L

#40 node modules 사용하도록 변경
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  .yarnrc.yml
Labels: bug, size/XXL, fix

#41 refactor: keyring 관련 코드 background -> controller 이동
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/ui/components/atoms/text-field/text-field.jsx
  src/ui/pages/import-account.jsx
  src/ui/pages/new-account.jsx
Labels: refactor, size/L

#47 feat: 계정 가져오기 기능 추가
  .yarn/cache/react-simple-file-input-npm-2.1.0-82dd122232-e4999623f8.zip
  package.json
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/lib/account-importer.js
  src/app/lib/util.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/pages/json-file.jsx
  yarn.lock
Labels: feature, size/L

#49 account 정보 store에 저장 기능 추가
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/messages.js
  src/ui/data/account/account.api.js
  src/ui/data/account/account.hooks.js
  src/ui/pages/home.jsx
  src/ui/pages/json-file.jsx
Labels: feature, size/L

#51 keyring-controller transaction sign 기능 추가
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/controllers/provider-controller.js
  src/app/controllers/transaction-controller.js
  src/app/lib/hd-keyring.js
  src/app/lib/simple-keyring.js
  src/ui/data/provider/provider.api.js
  src/ui/data/provider/provider.hooks.js
  src/ui/data/transaction/index.js
  src/ui/data/transaction/transaction.api.js
  src/ui/data/transaction/transaction.hooks.js
  src/ui/pages/json-file.jsx
  src/ui/pages/provider.jsx
Labels: feature, size/L
