Repository tf-wallet-dscanner/tf-wallet, pull requests merged in 2022-10, with the labels that each got.

#84 feat: 홈 공통 account view 컴포넌트 추가
  .eslintrc.js
  public/popup.html
  src/ui/components/account-view/account-view.jsx
  src/ui/components/account-view/account-view.scss
  src/ui/components/account-view/balance/balance.jsx
  src/ui/components/account-view/balance/index.js
  src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
  src/ui/components/account-view/dropdown-menu/dropdown-menu.scss
  src/ui/components/account-view/dropdown-menu/index.js
  src/ui/components/account-view/index.js
  src/ui/components/account-view/selected-account/index.js
  src/ui/components/account-view/selected-account/selected-account.jsx
  src/ui/components/account-view/selected-account/selected-account.scss
  src/ui/components/atoms/toast/toast.scss
  src/ui/components/atoms/tooltip/tooltip.jsx
  src/ui/components/atoms/tooltip/tooltip.scss
  src/ui/pages/home.jsx
  src/ui/pages/intro.jsx
  src/ui/pages/routing.jsx
Labels: feature, size/L

#88 feat: 계정 추가, 가져오기 페이지 개발
  src/app/background.js
  src/app/controller.js
  src/app/controllers/keyring-controller.js
  src/app/messages.js
  src/ui/components/account-view/balance/balance.jsx
  src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
  src/ui/data/account/account.api.js
  src/ui/data/account/account.hooks.js
  src/ui/pages/confirm-mnemonic.jsx
  src/ui/pages/create-mnemonic.jsx
  src/ui/pages/create-password.jsx
  src/ui/pages/export-account.jsx
  src/ui/pages/home.jsx
  src/ui/pages/import-account.jsx
  src/ui/pages/new-account.jsx
  src/ui/pages/provider.jsx
  src/ui/pages/routing.jsx
  src/ui/pages/unlock.jsx
  tailwind.config.js
Labels: refactor, feature, size/XL, fix

#92 Preview token
  src/app/controller.js
  src/app/controllers/token-controller.js
  src/ui/components/asset-list/asset-item/asset-item.jsx
  src/ui/components/asset-list/asset-list.jsx
  src/ui/pages/assets.jsx
  src/ui/pages/create-token.jsx
  src/ui/pages/transfer/estimate-token-gas.jsx
  src/ui/pages/transfer/input-address-token.jsx
Labels: size/L

#93 트랜잭션 내역 조회 페이지 개발
  src/app/constants/network.js
  src/app/controller.js
  src/app/controllers/history-controller.js
  src/ui/components/account-view/dropdown-menu/dropdown-menu.jsx
  src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.jsx
  src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.scss
  src/ui/components/eth-transaction-list/eth-transaction-item/index.js
  src/ui/components/eth-transaction-list/eth-transaction-list.jsx
  src/ui/components/eth-transaction-list/index.js
  src/ui/components/klay-transaction-list/index.js
  src/ui/components/klay-transaction-list/klay-transaction-item/index.js
  src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.jsx
  src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.scss
  src/ui/components/klay-transaction-list/klay-transaction-list.jsx
  src/ui/data/history/history.api.js
  src/ui/data/history/history.hooks.js
  src/ui/pages/assets.jsx
  src/ui/pages/home.jsx
  src/ui/pages/routing.jsx
  src/ui/pages/tx-history.jsx
  src/ui/pages/welcome.jsx
  tailwind.config.js
Labels: feature

#95 Mnemonic add account
  src/app/controllers/keyring-controller.js
  src/app/lib/hd-keyring.js
  src/ui/data/account/account.api.js
Labels: size/L

#97 refactor: history unit 수정
  src/app/controllers/history-controller.js
  src/ui/components/account-view/selected-account/selected-account.jsx
  src/ui/components/asset-list/asset-item/asset-item.jsx
  src/ui/components/asset-list/asset-item/asset-item.scss
  src/ui/components/eth-transaction-list/eth-transaction-item/eth-transaction-item.jsx
  src/ui/components/klay-transaction-list/klay-transaction-item/klay-transaction-item.jsx
  src/ui/data/history/history.hooks.js
  src/ui/pages/tx-history.jsx
Labels: refactor, feature, size/L
